-- *********************************************
-- THE "mosaic" SCHEMA
-- *********************************************
CREATE SCHEMA "mosaic";

-- TODO: create standard mosaic database objects

-- *********************************************
-- THE "it" SCHEMA
-- *********************************************
CREATE SCHEMA "it";

CREATE TABLE "it.it01_table1" (

  "id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) NOT NULL

);
