SET DATABASE DEFAULT TABLE TYPE MEMORY;
CREATE SCHEMA accounting;

-- =============================================================
-- Expense/Income categories
-- =============================================================
CREATE TABLE accounting.categories (

-- primary key, generated sequence starts with 1000 so we can add testing values below that
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1000 ) PRIMARY KEY,

-- general
    name VARCHAR(100) NOT NULL
);

-- =============================================================
-- External entities such as business places or income sources
-- =============================================================
CREATE TABLE accounting.external_entities (

-- primary key, generated sequence starts with 1000 so we can add testing values below that
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1000 ) PRIMARY KEY,

-- general
    name VARCHAR(100) NOT NULL
);

-- =============================================================
-- Transactions
-- =============================================================
CREATE TABLE accounting.transactions (

-- primary key, generated sequence starts with 1000 so we can add testing values below that
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1000 ) PRIMARY KEY,

-- general info
    name        VARCHAR(100)             NOT NULL,
    description VARCHAR(1000)            NULL,
    date        TIMESTAMP WITH TIME ZONE NOT NULL,
    category_id INTEGER                  NULL,
    entity_id   INTEGER                  NULL,
    amount      DECIMAL                  NOT NULL,

-- foreign keys
    CONSTRAINT expenses_categories_fk FOREIGN KEY (category_id) REFERENCES accounting.categories (id)
        ON DELETE SET NULL
        ON UPDATE RESTRICT,
    CONSTRAINT expenses_external_entities_fk FOREIGN KEY (entity_id) REFERENCES accounting.external_entities (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);
